# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yv9Tx2xs-2gdvx3tHFHqvbU4GRJNKHBk
"""

import streamlit as st

# Title
st.title("BMI Calculator App")

st.write("Enter your details below:")

# User Inputs
name = st.text_input("Enter your name")
age = st.number_input("Enter your age", min_value=1, max_value=120)
gender = st.selectbox("Select your gender", ["Male", "Female"])
height = st.number_input("Enter your height (in meters)", min_value=0.5, max_value=2.5)
weight = st.number_input("Enter your weight (in kg)", min_value=10.0, max_value=200.0)

# Calculate BMI
if st.button("Calculate BMI"):
    if height > 0:
        bmi = weight / (height ** 2)
        st.success(f"Hello {name}, your BMI is: {bmi:.2f}")

        # Categorization
        if bmi < 18.5:
            category = "Underweight"
            st.warning("You are Underweight")
            st.write("### Suggested Meal Plan")
            st.write("- Eat high-protein foods")
            st.write("- Include nuts and dairy products")
            st.write("- Eat more calories frequently")
            st.write("### Suggested Exercises")
            st.write("- Strength training")
            st.write("- Light cardio")

        elif 18.5 <= bmi <= 24.9:
            category = "Normal"
            st.success("You have Normal weight")
            st.write("### Suggested Meal Plan")
            st.write("- Balanced diet")
            st.write("- Fruits and vegetables")
            st.write("- Whole grains")
            st.write("### Suggested Exercises")
            st.write("- Jogging")
            st.write("- Yoga")
            st.write("- Cycling")

        else:
            category = "Overweight"
            st.error("You are Overweight")
            st.write("### Suggested Meal Plan")
            st.write("- Low calorie diet")
            st.write("- Avoid sugary foods")
            st.write("- Increase protein intake")
            st.write("### Suggested Exercises")
            st.write("- Running")
            st.write("- Swimming")
            st.write("- HIIT workouts")

    else:
        st.error("Height must be greater than zero")